<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIKx8h7x\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIKx8h7x/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerIKx8h7x.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerIKx8h7x\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerIKx8h7x\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'IKx8h7x',
    'container.build_id' => '990b8307',
    'container.build_time' => 1650506200,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIKx8h7x');
