<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHFXBhqR\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHFXBhqR/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHFXBhqR.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHFXBhqR\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerHFXBhqR\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'HFXBhqR',
    'container.build_id' => '33fce662',
    'container.build_time' => 1649900931,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHFXBhqR');
